// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: protobuf/grpc.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reply2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stock   bool       `protobuf:"varint,1,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Changes []*Changes `protobuf:"bytes,2,rep,name=Changes,proto3" json:"Changes,omitempty"`
	Bill    []string   `protobuf:"bytes,3,rep,name=bill,proto3" json:"bill,omitempty"`
	Err     string     `protobuf:"bytes,4,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *Reply2) Reset() {
	*x = Reply2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reply2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply2) ProtoMessage() {}

func (x *Reply2) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply2.ProtoReflect.Descriptor instead.
func (*Reply2) Descriptor() ([]byte, []int) {
	return file_protobuf_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *Reply2) GetStock() bool {
	if x != nil {
		return x.Stock
	}
	return false
}

func (x *Reply2) GetChanges() []*Changes {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *Reply2) GetBill() []string {
	if x != nil {
		return x.Bill
	}
	return nil
}

func (x *Reply2) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type Changes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value  int64 `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	Amount int64 `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
}

func (x *Changes) Reset() {
	*x = Changes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Changes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Changes) ProtoMessage() {}

func (x *Changes) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Changes.ProtoReflect.Descriptor instead.
func (*Changes) Descriptor() ([]byte, []int) {
	return file_protobuf_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *Changes) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Changes) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Request2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cart          *Cart2   `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	Paid          int64    `protobuf:"varint,2,opt,name=paid,proto3" json:"paid,omitempty"`
	PaymentMethod string   `protobuf:"bytes,3,opt,name=paymentMethod,proto3" json:"paymentMethod,omitempty"`
	Type          string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Geo           *GeoJson `protobuf:"bytes,5,opt,name=geo,proto3" json:"geo,omitempty"`
}

func (x *Request2) Reset() {
	*x = Request2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request2) ProtoMessage() {}

func (x *Request2) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request2.ProtoReflect.Descriptor instead.
func (*Request2) Descriptor() ([]byte, []int) {
	return file_protobuf_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *Request2) GetCart() *Cart2 {
	if x != nil {
		return x.Cart
	}
	return nil
}

func (x *Request2) GetPaid() int64 {
	if x != nil {
		return x.Paid
	}
	return 0
}

func (x *Request2) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *Request2) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Request2) GetGeo() *GeoJson {
	if x != nil {
		return x.Geo
	}
	return nil
}

type GeoJson struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string  `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Long float32 `protobuf:"fixed32,2,opt,name=long,proto3" json:"long,omitempty"`
	Lat  float32 `protobuf:"fixed32,3,opt,name=lat,proto3" json:"lat,omitempty"`
}

func (x *GeoJson) Reset() {
	*x = GeoJson{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_grpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeoJson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoJson) ProtoMessage() {}

func (x *GeoJson) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_grpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoJson.ProtoReflect.Descriptor instead.
func (*GeoJson) Descriptor() ([]byte, []int) {
	return file_protobuf_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *GeoJson) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GeoJson) GetLong() float32 {
	if x != nil {
		return x.Long
	}
	return 0
}

func (x *GeoJson) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

type Cart2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId string   `protobuf:"bytes,2,opt,name=customerId,proto3" json:"customerId,omitempty"`
	Menu       []*Menu2 `protobuf:"bytes,3,rep,name=menu,proto3" json:"menu,omitempty"`
	Price      int64    `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *Cart2) Reset() {
	*x = Cart2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_grpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cart2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cart2) ProtoMessage() {}

func (x *Cart2) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_grpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cart2.ProtoReflect.Descriptor instead.
func (*Cart2) Descriptor() ([]byte, []int) {
	return file_protobuf_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *Cart2) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cart2) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Cart2) GetMenu() []*Menu2 {
	if x != nil {
		return x.Menu
	}
	return nil
}

func (x *Cart2) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type Menu2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Category   []string       `protobuf:"bytes,2,rep,name=category,proto3" json:"category,omitempty"`
	Name       string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Ingredient []*Ingredient2 `protobuf:"bytes,4,rep,name=ingredient,proto3" json:"ingredient,omitempty"`
	Price      int64          `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Available  bool           `protobuf:"varint,6,opt,name=available,proto3" json:"available,omitempty"`
	Amount     int64          `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Option     string         `protobuf:"bytes,8,opt,name=option,proto3" json:"option,omitempty"`
}

func (x *Menu2) Reset() {
	*x = Menu2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_grpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Menu2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu2) ProtoMessage() {}

func (x *Menu2) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_grpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu2.ProtoReflect.Descriptor instead.
func (*Menu2) Descriptor() ([]byte, []int) {
	return file_protobuf_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *Menu2) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Menu2) GetCategory() []string {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *Menu2) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Menu2) GetIngredient() []*Ingredient2 {
	if x != nil {
		return x.Ingredient
	}
	return nil
}

func (x *Menu2) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Menu2) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *Menu2) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Menu2) GetOption() string {
	if x != nil {
		return x.Option
	}
	return ""
}

type Ingredient2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IngredientName string `protobuf:"bytes,1,opt,name=ingredientName,proto3" json:"ingredientName,omitempty"`
	Amount         int64  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *Ingredient2) Reset() {
	*x = Ingredient2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_grpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ingredient2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ingredient2) ProtoMessage() {}

func (x *Ingredient2) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_grpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ingredient2.ProtoReflect.Descriptor instead.
func (*Ingredient2) Descriptor() ([]byte, []int) {
	return file_protobuf_grpc_proto_rawDescGZIP(), []int{6}
}

func (x *Ingredient2) GetIngredientName() string {
	if x != nil {
		return x.IngredientName
	}
	return ""
}

func (x *Ingredient2) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_protobuf_grpc_proto protoreflect.FileDescriptor

var file_protobuf_grpc_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x61, 0x72, 0x74, 0x22, 0x6d, 0x0a, 0x06, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x27, 0x0a, 0x07, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63,
	0x61, 0x72, 0x74, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x52, 0x07, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x37, 0x0a, 0x07, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x9a, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x32,
	0x12, 0x1f, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x32, 0x52, 0x04, 0x63, 0x61, 0x72,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x70, 0x61, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x1f, 0x0a, 0x03, 0x67, 0x65, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63,
	0x61, 0x72, 0x74, 0x2e, 0x47, 0x65, 0x6f, 0x4a, 0x73, 0x6f, 0x6e, 0x52, 0x03, 0x67, 0x65, 0x6f,
	0x22, 0x43, 0x0a, 0x07, 0x47, 0x65, 0x6f, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x6c,
	0x6f, 0x6e, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x03, 0x6c, 0x61, 0x74, 0x22, 0x6e, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x74, 0x32, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f,
	0x0a, 0x04, 0x6d, 0x65, 0x6e, 0x75, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63,
	0x61, 0x72, 0x74, 0x2e, 0x6d, 0x65, 0x6e, 0x75, 0x32, 0x52, 0x04, 0x6d, 0x65, 0x6e, 0x75, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0xde, 0x01, 0x0a, 0x05, 0x6d, 0x65, 0x6e, 0x75, 0x32, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x31, 0x0a, 0x0a, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x69, 0x6e, 0x67, 0x72, 0x65,
	0x64, 0x69, 0x65, 0x6e, 0x74, 0x32, 0x52, 0x0a, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65,
	0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4d, 0x0a, 0x0b, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x64,
	0x69, 0x65, 0x6e, 0x74, 0x32, 0x12, 0x26, 0x0a, 0x0e, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69,
	0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x69,
	0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x34, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x61, 0x72,
	0x74, 0x12, 0x28, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x74, 0x12, 0x0e, 0x2e,
	0x63, 0x61, 0x72, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x32, 0x1a, 0x0c, 0x2e,
	0x63, 0x61, 0x72, 0x74, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x42, 0x07, 0x5a, 0x05, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_grpc_proto_rawDescOnce sync.Once
	file_protobuf_grpc_proto_rawDescData = file_protobuf_grpc_proto_rawDesc
)

func file_protobuf_grpc_proto_rawDescGZIP() []byte {
	file_protobuf_grpc_proto_rawDescOnce.Do(func() {
		file_protobuf_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_grpc_proto_rawDescData)
	})
	return file_protobuf_grpc_proto_rawDescData
}

var file_protobuf_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protobuf_grpc_proto_goTypes = []interface{}{
	(*Reply2)(nil),      // 0: cart.Reply2
	(*Changes)(nil),     // 1: cart.Changes
	(*Request2)(nil),    // 2: cart.Request2
	(*GeoJson)(nil),     // 3: cart.GeoJson
	(*Cart2)(nil),       // 4: cart.cart2
	(*Menu2)(nil),       // 5: cart.menu2
	(*Ingredient2)(nil), // 6: cart.ingredient2
}
var file_protobuf_grpc_proto_depIdxs = []int32{
	1, // 0: cart.Reply2.Changes:type_name -> cart.Changes
	4, // 1: cart.Request2.cart:type_name -> cart.cart2
	3, // 2: cart.Request2.geo:type_name -> cart.GeoJson
	5, // 3: cart.cart2.menu:type_name -> cart.menu2
	6, // 4: cart.menu2.ingredient:type_name -> cart.ingredient2
	2, // 5: cart.SendCart.SendCart:input_type -> cart.Request2
	0, // 6: cart.SendCart.SendCart:output_type -> cart.Reply2
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_protobuf_grpc_proto_init() }
func file_protobuf_grpc_proto_init() {
	if File_protobuf_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reply2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Changes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_grpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_grpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeoJson); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_grpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cart2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_grpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Menu2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_grpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ingredient2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_grpc_proto_goTypes,
		DependencyIndexes: file_protobuf_grpc_proto_depIdxs,
		MessageInfos:      file_protobuf_grpc_proto_msgTypes,
	}.Build()
	File_protobuf_grpc_proto = out.File
	file_protobuf_grpc_proto_rawDesc = nil
	file_protobuf_grpc_proto_goTypes = nil
	file_protobuf_grpc_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SendCartClient is the client API for SendCart service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SendCartClient interface {
	SendCart(ctx context.Context, in *Request2, opts ...grpc.CallOption) (*Reply2, error)
}

type sendCartClient struct {
	cc grpc.ClientConnInterface
}

func NewSendCartClient(cc grpc.ClientConnInterface) SendCartClient {
	return &sendCartClient{cc}
}

func (c *sendCartClient) SendCart(ctx context.Context, in *Request2, opts ...grpc.CallOption) (*Reply2, error) {
	out := new(Reply2)
	err := c.cc.Invoke(ctx, "/cart.SendCart/SendCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendCartServer is the server API for SendCart service.
type SendCartServer interface {
	SendCart(context.Context, *Request2) (*Reply2, error)
}

// UnimplementedSendCartServer can be embedded to have forward compatible implementations.
type UnimplementedSendCartServer struct {
}

func (*UnimplementedSendCartServer) SendCart(context.Context, *Request2) (*Reply2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCart not implemented")
}

func RegisterSendCartServer(s *grpc.Server, srv SendCartServer) {
	s.RegisterService(&_SendCart_serviceDesc, srv)
}

func _SendCart_SendCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendCartServer).SendCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cart.SendCart/SendCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendCartServer).SendCart(ctx, req.(*Request2))
	}
	return interceptor(ctx, in, info, handler)
}

var _SendCart_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cart.SendCart",
	HandlerType: (*SendCartServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCart",
			Handler:    _SendCart_SendCart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/grpc.proto",
}
