// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: protobuf/oauth/oauth.proto

package oauth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RevokeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_oauth_oauth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_oauth_oauth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_oauth_oauth_proto_rawDescGZIP(), []int{0}
}

func (x *RevokeRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type RevokeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *RevokeReply) Reset() {
	*x = RevokeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_oauth_oauth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevokeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeReply) ProtoMessage() {}

func (x *RevokeReply) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_oauth_oauth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeReply.ProtoReflect.Descriptor instead.
func (*RevokeReply) Descriptor() ([]byte, []int) {
	return file_protobuf_oauth_oauth_proto_rawDescGZIP(), []int{1}
}

func (x *RevokeReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_protobuf_oauth_oauth_proto protoreflect.FileDescriptor

var file_protobuf_oauth_oauth_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6f, 0x61, 0x75, 0x74, 0x68,
	0x2f, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6f, 0x61,
	0x75, 0x74, 0x68, 0x22, 0x27, 0x0a, 0x0d, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x25, 0x0a, 0x0b,
	0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x32, 0x40, 0x0a, 0x05, 0x4f, 0x61, 0x75, 0x74, 0x68, 0x12, 0x37, 0x0a, 0x0b,
	0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x2e, 0x6f, 0x61,
	0x75, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x12, 0x2e, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_oauth_oauth_proto_rawDescOnce sync.Once
	file_protobuf_oauth_oauth_proto_rawDescData = file_protobuf_oauth_oauth_proto_rawDesc
)

func file_protobuf_oauth_oauth_proto_rawDescGZIP() []byte {
	file_protobuf_oauth_oauth_proto_rawDescOnce.Do(func() {
		file_protobuf_oauth_oauth_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_oauth_oauth_proto_rawDescData)
	})
	return file_protobuf_oauth_oauth_proto_rawDescData
}

var file_protobuf_oauth_oauth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_oauth_oauth_proto_goTypes = []interface{}{
	(*RevokeRequest)(nil), // 0: oauth.RevokeRequest
	(*RevokeReply)(nil),   // 1: oauth.RevokeReply
}
var file_protobuf_oauth_oauth_proto_depIdxs = []int32{
	0, // 0: oauth.Oauth.RevokeToken:input_type -> oauth.RevokeRequest
	1, // 1: oauth.Oauth.RevokeToken:output_type -> oauth.RevokeReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_oauth_oauth_proto_init() }
func file_protobuf_oauth_oauth_proto_init() {
	if File_protobuf_oauth_oauth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_oauth_oauth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevokeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_oauth_oauth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevokeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_oauth_oauth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_oauth_oauth_proto_goTypes,
		DependencyIndexes: file_protobuf_oauth_oauth_proto_depIdxs,
		MessageInfos:      file_protobuf_oauth_oauth_proto_msgTypes,
	}.Build()
	File_protobuf_oauth_oauth_proto = out.File
	file_protobuf_oauth_oauth_proto_rawDesc = nil
	file_protobuf_oauth_oauth_proto_goTypes = nil
	file_protobuf_oauth_oauth_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OauthClient is the client API for Oauth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OauthClient interface {
	RevokeToken(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeReply, error)
}

type oauthClient struct {
	cc grpc.ClientConnInterface
}

func NewOauthClient(cc grpc.ClientConnInterface) OauthClient {
	return &oauthClient{cc}
}

func (c *oauthClient) RevokeToken(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeReply, error) {
	out := new(RevokeReply)
	err := c.cc.Invoke(ctx, "/oauth.Oauth/RevokeToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OauthServer is the server API for Oauth service.
type OauthServer interface {
	RevokeToken(context.Context, *RevokeRequest) (*RevokeReply, error)
}

// UnimplementedOauthServer can be embedded to have forward compatible implementations.
type UnimplementedOauthServer struct {
}

func (*UnimplementedOauthServer) RevokeToken(context.Context, *RevokeRequest) (*RevokeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeToken not implemented")
}

func RegisterOauthServer(s *grpc.Server, srv OauthServer) {
	s.RegisterService(&_Oauth_serviceDesc, srv)
}

func _Oauth_RevokeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OauthServer).RevokeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oauth.Oauth/RevokeToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OauthServer).RevokeToken(ctx, req.(*RevokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Oauth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oauth.Oauth",
	HandlerType: (*OauthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RevokeToken",
			Handler:    _Oauth_RevokeToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/oauth/oauth.proto",
}
