// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: protobuf/middleware.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestMiddleware struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path   string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *RequestMiddleware) Reset() {
	*x = RequestMiddleware{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_middleware_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestMiddleware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMiddleware) ProtoMessage() {}

func (x *RequestMiddleware) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_middleware_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMiddleware.ProtoReflect.Descriptor instead.
func (*RequestMiddleware) Descriptor() ([]byte, []int) {
	return file_protobuf_middleware_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMiddleware) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RequestMiddleware) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestMiddleware) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReplyMiddleware struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Allow bool `protobuf:"varint,1,opt,name=allow,proto3" json:"allow,omitempty"`
}

func (x *ReplyMiddleware) Reset() {
	*x = ReplyMiddleware{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_middleware_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyMiddleware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMiddleware) ProtoMessage() {}

func (x *ReplyMiddleware) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_middleware_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMiddleware.ProtoReflect.Descriptor instead.
func (*ReplyMiddleware) Descriptor() ([]byte, []int) {
	return file_protobuf_middleware_proto_rawDescGZIP(), []int{1}
}

func (x *ReplyMiddleware) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

var File_protobuf_middleware_proto protoreflect.FileDescriptor

var file_protobuf_middleware_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6d, 0x69, 0x64, 0x64, 0x6c,
	0x65, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x55, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x27, 0x0a, 0x0f,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x32, 0x52, 0x0a, 0x0a, 0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77,
	0x61, 0x72, 0x65, 0x12, 0x44, 0x0a, 0x0a, 0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72,
	0x65, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x1a, 0x19,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4d,
	0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_middleware_proto_rawDescOnce sync.Once
	file_protobuf_middleware_proto_rawDescData = file_protobuf_middleware_proto_rawDesc
)

func file_protobuf_middleware_proto_rawDescGZIP() []byte {
	file_protobuf_middleware_proto_rawDescOnce.Do(func() {
		file_protobuf_middleware_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_middleware_proto_rawDescData)
	})
	return file_protobuf_middleware_proto_rawDescData
}

var file_protobuf_middleware_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_middleware_proto_goTypes = []interface{}{
	(*RequestMiddleware)(nil), // 0: protobuf.RequestMiddleware
	(*ReplyMiddleware)(nil),   // 1: protobuf.ReplyMiddleware
}
var file_protobuf_middleware_proto_depIdxs = []int32{
	0, // 0: protobuf.Middleware.Middleware:input_type -> protobuf.RequestMiddleware
	1, // 1: protobuf.Middleware.Middleware:output_type -> protobuf.ReplyMiddleware
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_middleware_proto_init() }
func file_protobuf_middleware_proto_init() {
	if File_protobuf_middleware_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_middleware_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestMiddleware); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_middleware_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyMiddleware); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_middleware_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_middleware_proto_goTypes,
		DependencyIndexes: file_protobuf_middleware_proto_depIdxs,
		MessageInfos:      file_protobuf_middleware_proto_msgTypes,
	}.Build()
	File_protobuf_middleware_proto = out.File
	file_protobuf_middleware_proto_rawDesc = nil
	file_protobuf_middleware_proto_goTypes = nil
	file_protobuf_middleware_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MiddlewareClient is the client API for Middleware service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MiddlewareClient interface {
	Middleware(ctx context.Context, in *RequestMiddleware, opts ...grpc.CallOption) (*ReplyMiddleware, error)
}

type middlewareClient struct {
	cc grpc.ClientConnInterface
}

func NewMiddlewareClient(cc grpc.ClientConnInterface) MiddlewareClient {
	return &middlewareClient{cc}
}

func (c *middlewareClient) Middleware(ctx context.Context, in *RequestMiddleware, opts ...grpc.CallOption) (*ReplyMiddleware, error) {
	out := new(ReplyMiddleware)
	err := c.cc.Invoke(ctx, "/protobuf.Middleware/Middleware", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MiddlewareServer is the server API for Middleware service.
type MiddlewareServer interface {
	Middleware(context.Context, *RequestMiddleware) (*ReplyMiddleware, error)
}

// UnimplementedMiddlewareServer can be embedded to have forward compatible implementations.
type UnimplementedMiddlewareServer struct {
}

func (*UnimplementedMiddlewareServer) Middleware(context.Context, *RequestMiddleware) (*ReplyMiddleware, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Middleware not implemented")
}

func RegisterMiddlewareServer(s *grpc.Server, srv MiddlewareServer) {
	s.RegisterService(&_Middleware_serviceDesc, srv)
}

func _Middleware_Middleware_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMiddleware)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddlewareServer).Middleware(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Middleware/Middleware",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddlewareServer).Middleware(ctx, req.(*RequestMiddleware))
	}
	return interceptor(ctx, in, info, handler)
}

var _Middleware_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Middleware",
	HandlerType: (*MiddlewareServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Middleware",
			Handler:    _Middleware_Middleware_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/middleware.proto",
}
