// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package domain

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetMenuClient is the client API for GetMenu service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetMenuClient interface {
	Menu(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type getMenuClient struct {
	cc grpc.ClientConnInterface
}

func NewGetMenuClient(cc grpc.ClientConnInterface) GetMenuClient {
	return &getMenuClient{cc}
}

func (c *getMenuClient) Menu(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/cart.GetMenu/Menu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetMenuServer is the server API for GetMenu service.
// All implementations must embed UnimplementedGetMenuServer
// for forward compatibility
type GetMenuServer interface {
	Menu(context.Context, *Request) (*Reply, error)
	mustEmbedUnimplementedGetMenuServer()
}

// UnimplementedGetMenuServer must be embedded to have forward compatible implementations.
type UnimplementedGetMenuServer struct {
}

func (UnimplementedGetMenuServer) Menu(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Menu not implemented")
}
func (UnimplementedGetMenuServer) mustEmbedUnimplementedGetMenuServer() {}

// UnsafeGetMenuServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetMenuServer will
// result in compilation errors.
type UnsafeGetMenuServer interface {
	mustEmbedUnimplementedGetMenuServer()
}

func RegisterGetMenuServer(s grpc.ServiceRegistrar, srv GetMenuServer) {
	s.RegisterService(&GetMenu_ServiceDesc, srv)
}

func _GetMenu_Menu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetMenuServer).Menu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cart.GetMenu/Menu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetMenuServer).Menu(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// GetMenu_ServiceDesc is the grpc.ServiceDesc for GetMenu service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetMenu_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cart.GetMenu",
	HandlerType: (*GetMenuServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Menu",
			Handler:    _GetMenu_Menu_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cart.proto",
}
