# Default values for generic-deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.touchdevops.com/authorization
  tag: "1.0"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - nexus-jenkins-secret

nameOverride: authorization-service
fullnameOverride: authorization-service

env:
  - name: APP_ENV
    value: "dev"
  - name: MONGODB_ENDPOINT
    value: "mongodb://root:UZiYgNT6ZeBo9Jxs@mongodb-dev:27017"
  - name: MONGODB_NAME
    value: "authorization_service"
  - name: MONGODB_ROLE_TABLE_NAME
    value: "roles"
  - name: MONGODB_PERMISSION_TABLE_NAME
    value: "permissions"
  - name: APP_NAME
    value: "authorization-service"
  - name: TIMEZONE
    value: "asia/bangkok"
  - name: JAEGER_AGENT_HOST
    value: "jaeger-infra-agent.infra"
  - name: JAEGER_AGENT_PORT
    value: 6831
  - name: UID_HEADER_NAME
    value: "X-Authenticated-Userid"
  - name: SWAGGER_HOST
    value: "mediator.touchdevops.com/dev/authorization"
  - name: BASE_PATHS
    value: "/api/v1"
  - name: DEFAULT_LANGUAGE
    value: "th"
  - name: GRPC_HOST
    value: "authentication-service.dev:50051"

envFrom: { }
# configMaps:
#   - generic-deployment
# secrets:
#   - generic-deployment

configMaps:
  create: false
  data: { }
  # SAMPLE_CONFIG: "sample-config"

secrets:
  create: false
  data: { }
  # SAMPLE_PASSWORD: "sample-secret"

containerPorts:
  - 8080

resources: { }
# requests:
#   cpu: 100m
#   memory: 50Mi
# limits:
#   cpu: 2000m
#   memory: 200Mi

nodeSelector: { }

tolerations: [ ]

affinity: { }

# Waiting time in seconds for shutting down pod after sent SIGTERM
terminationGracePeriodSeconds: 30

services:
  - type: ClusterIP
    annotation: { }
    ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: 8080
  # - suffixName: "lb"
  #   type: LoadBalancer
  #   annotation: {}
  #   ports:
  #     - name: sample1-service-port
  #       protocol: TCP
  #       port: 80
  #       targetPort: 80
  #     - name: sample2-service-port
  #       protocol: TCP
  #       port: 8080
  #       targetPort: 8080

serviceHeadless:
  enabled: false
  # annotation: {}
  # ports:
  #   - name: sample1-service-port
  #     protocol: TCP
  #     port: 80
  #     targetPort: 80
  #   - name: sample2-service-port
  #     protocol: TCP
  #     port: 8080
  #     targetPort: 8080

healthCheck:
  enabled: true
  readinessProbe:
    httpGet:
      path: /system/health
      port: 8080
    initialDelaySeconds: 0
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  livenessProbe:
    httpGet:
      path: /system/health
      port: 8080
    initialDelaySeconds: 0
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3



# Pod update strategy
updateStrategy:
  # Blue-Green Deployment
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 100%
    maxUnavailable: 0

# Horizontal Pod Autoscaling
autoscaling:
  enabled: false
  # # Example
  # minReplicas: 1
  # maxReplicas: 10
  # targetCPUUtilizationPercentage: 50
  # targetMemoryUtilizationPercentage: 50