version: '3'
services: # each service run simultaneously (parallel)
  menudb:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    environment:
      #      - node.name=menu
      #      - cluster.name=es-docker-cluster
      - discovery.type=single-node
    #      - cluster.initial_master_nodes=es01,es02,es03
    #      - bootstrap.memory_lock=true
    #      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    #    volumes:
    #      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    env_file:
      - kibana.env
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://menudb:9200
      ELASTICSEARCH_HOSTS: http://menudb:9200
    depends_on:
      - menudb

  redis:
    image: "redis"
    ports:
      - "6379:6379"